/**
 * This file would be statically generated by Oriql. It can be placed anywhere; in the same folder, in a different repo, or even somewhere over a network
 */
export namespace PropTypes {
  export interface HelloComponent {
    compiler?: string | null | undefined;
    framework?: string | null | undefined;
    foo?: | {foo: string} | null | undefined
  }
  export interface Hello extends HelloComponent {}
}