/**
 * This file would be statically generated by Oriql. It can be placed anywhere; in the same folder, in a different repo, or even somewhere over a network
 */
export default {
  instances: {
    HelloComponent: "HelloComponent",
    Hello: "HelloComponent",
  },
  queries: { HelloComponent: "HelloComponent { compiler framework }" }
};